// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7gfBhi1dwwnp3EOKUJW-L04A69skOuBE',
    appId: '1:99638042402:web:56804e0ec3c374e8f30f7b',
    messagingSenderId: '99638042402',
    projectId: 'todo-sync-app-25188',
    authDomain: 'todo-sync-app-25188.firebaseapp.com',
    storageBucket: 'todo-sync-app-25188.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdsrNzUDlzDtsWjIAOqGalL8LuPgpLC5o',
    appId: '1:99638042402:android:80cbe5064deaba32f30f7b',
    messagingSenderId: '99638042402',
    projectId: 'todo-sync-app-25188',
    storageBucket: 'todo-sync-app-25188.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7gfBhi1dwwnp3EOKUJW-L04A69skOuBE',
    appId: '1:99638042402:web:ae6e167e494e8d96f30f7b',
    messagingSenderId: '99638042402',
    projectId: 'todo-sync-app-25188',
    authDomain: 'todo-sync-app-25188.firebaseapp.com',
    storageBucket: 'todo-sync-app-25188.firebasestorage.app',
  );
}
